### ISSUE TITLE
User Administration does not exist?!

### ISSUE THREAD

**Issue by palminha** [IQSS/dataverse-docker#78]
I just followed the instructions to install dataverse using docker.
I can successfully connect to it via http://my.ip.address:8080/ and login as admin user
 
The problem is that i can't find what is described in the documentation  "_clicking the “Manage Users” button on the [Dashboard](https://guides.dataverse.org/en/latest/admin/dashboard.html), which is linked from the header of all Dataverse installation pages_"

![Screenshot 2022-12-05 at 10 03 15](https://user-images.githubusercontent.com/12155015/205609571-8345f77f-0e9b-4ef1-9a86-f0189acaab54.png)

**Comment by pdurbin** [comment]
Huh. That's weird. I expect to see "Dataverse Admin" in red, which indicates that it's a superuser. Like this:

![Screen Shot 2022-12-05 at 2 20 28 PM](https://user-images.githubusercontent.com/21006/205724380-03d4d5f1-91a4-4178-9ae8-66e29c763196.png)

I guess you could try "toggle superuser" API ([docs here](https://guides.dataverse.org/en/5.12.1/api/native-api.html#make-user-a-superuser)). You should see output like this:

$ curl -X POST "http://localhost:8080/api/admin/superuser/dataverseAdmin"
{"status":"OK","data":{"message":"User @dataverseAdmin removed as a superuser."}}

$ curl -X POST "http://localhost:8080/api/admin/superuser/dataverseAdmin"
{"status":"OK","data":{"message":"User @dataverseAdmin set as a superuser."}}

I'm not sure what happened to your Dataverse Admin user though. I'm not sure what the root of the problem is.

**Comment by palminha** [comment]
Hi Philip,

Thanks for following up.

I just tried it ... i had to instruct the command 3 times

***@***.***:~# docker exec -it 2d84d3392370 /bin/bash

***@***.***:/opt/payara/dvinstall# curl

curl: try 'curl --help' or 'curl --manual' for more information

***@***.***:/opt/payara/dvinstall# curl -X POST "
http://localhost:8080/api/admin/superuser/dataverseAdmin"

{"status":"OK","data":{"message":"User @dataverseAdmin set as a
***@***.***:/opt/payara/dvinstall#

***@***.***:/opt/payara/dvinstall#

***@***.***:/opt/payara/dvinstall#

***@***.***:/opt/payara/dvinstall# curl -X POST "
http://localhost:8080/api/admin/superuser/dataverseAdmin"

{"status":"OK","data":{"message":"User @dataverseAdmin removed as a
***@***.***:/opt/payara/dvinstall#

***@***.***:/opt/payara/dvinstall#

***@***.***:/opt/payara/dvinstall# curl -X POST "
http://localhost:8080/api/admin/superuser/dataverseAdmin"

{"status":"OK","data":{"message":"User @dataverseAdmin set as a
***@***.***:/opt/payara/dvinstall#

***@***.***:/opt/payara/dvinstall#

**Comment by pdurbin** [comment]
@palminha ok. And now it's working? You can see the superuser dashboard?

**Comment by pdurbin** [comment]
@palminha great! I'll go ahead and close this then.

If you or anyone else reading this sees this happen again (dataverseAdmin is not a superuser) please open a fresh issue. Thanks!

**Comment by ebergasa** [comment]
I have just had this same issue.
Quick vanilla installation following [these instructions](https://github.com/IQSS/dataverse-docker) of version 5.13 build 1244-79d6e57

Solved with 

```
[dialnet@pciencia-staging-5ec ~]$ docker exec -ti dataverse /bin/bash
root@08d8428cf537:/opt/payara/dvinstall# curl -X POST "http://localhost:8080/api/admin/superuser/dataverseAdmin"
{"status":"OK","data":{"message":"User @dataverseAdmin set as a superuser."}}
root@08d8428cf537:/opt/payara/dvinstall# curl -X POST "http://localhost:8080/api/admin/superuser/dataverseAdmin"
{"status":"OK","data":{"message":"User @dataverseAdmin removed as a superuser."}}
root@08d8428cf537:/opt/payara/dvinstall# curl -X POST "http://localhost:8080/api/admin/superuser/dataverseAdmin"
{"status":"OK","data":{"message":"User @dataverseAdmin set as a superuser."}}
```

**Comment by pdurbin** [comment]
@4tikhonov I probably closed this issue prematurely. It seems like it's still happening. Re-opening.

On a related note, what we probably at https://github.com/IQSS/dataverse/issues is an issue to implement an idempotent API call for making a user a superuser. Right now it's a toggle, which is annoying. 😬 If anyone wants to open this issue, please go ahead! ❤️

**Comment by jorgelpolanco** [comment]
I have just done the installation and can confirm that it is still happening. I followed @ebergasa's instructions and it worked for me. 

> @4tikhonov I probably closed this issue prematurely. It seems like it's still happening. Re-opening.
> 
> On a related note, what we probably at https://github.com/IQSS/dataverse/issues is an issue to implement an idempotent API call for making a user a superuser. Right now it's a toggle, which is annoying. 😬 If anyone wants to open this issue, please go ahead! ❤️

**Comment by pdurbin** [comment]
@jorgelpolanco thanks. Do you want to create the issue at https://github.com/IQSS/dataverse/issues I mentioned? 🙏

**Comment by markwilkinson** [comment]
I'm not sure if this is related or not...  using  5.13 build 1244-79d6e57

I start the docker-compose, enter the dataverseAdmin/admin credentials and am then sent to a "reset password" page.  This is fine, but it will not allow me to reset my password until I accept the terms of use... but there is no box to click to accept the terms of use, so I am stuck not being able to get started.

**Comment by 4tikhonov** [comment]
That's strange, let me check this @markwilkinson.

**Comment by markwilkinson** [comment]
Morning!  Have you had any thoughts about this problem?  My project is stalled until I can overcome this barrier...
thanks!

**Comment by pdurbin** [comment]
@markwilkinson as a workaround, when this happens, are you able to get a shell on the container running Dataverse and toggle the superuser on with curl? Here's an example:

https://github.com/IQSS/dataverse-docker/issues/78#issuecomment-1549662669

Longer term I'd like Dataverse to simply allow a boolean for promoting a user into a superuser:

- https://github.com/IQSS/dataverse/issues/9887

This would be more reliable than a toggle.

**Comment by mr-loop-1** [comment]
Hi @ebergasa @palminha , you both mentioned about calling the api 3 times. But this api is toggle based, so once was enough too, as I am able to check.

**Comment by 4tikhonov** [comment]
Hi @markwilkinson @ebergasa @adkinsrs  @mr-loop-1, we'll fix with in the new release to enable superuser account by default.

**Comment by markwilkinson** [comment]
> @markwilkinson as a workaround, when this happens, are you able to get a shell on the container running Dataverse and toggle the superuser on with curl? Here's an example:
> 
> [#78 (comment)](https://github.com/IQSS/dataverse-docker/issues/78#issuecomment-1549662669)
> 
> Longer term I'd like Dataverse to simply allow a boolean for promoting a user into a superuser:
> 
>     * [idempotent API call for making a user a superuser dataverse#9887](https://github.com/IQSS/dataverse/issues/9887)
> 
> 
> This would be more reliable than a toggle.

Hi Philip!

This didn't solve the problem - I was still unable to get past the password-change request.  However, I created another user, and toggled that user (via curl) to be a superuser, and that got me a long way down the road :-)

Cheers!

Mark

**Comment by pdurbin** [comment]
@markwilkinson hmm, the password reset problem seems a bit different. It might be nice to have a dedicated issue about that.

I'm glad creating the second user worked!

**Comment by pdurbin** [comment]
@palminha @adkinsrs @ebergasa @jorgelpolanco @markwilkinson @4tikhonov there's a new pull request by @zearaujo25 upstream that I just approved:

- https://github.com/IQSS/dataverse/pull/10440

**Comment by pdurbin** [comment]
Merged!

**Comment by markwilkinson** [comment]
Just FYI - v. 5.13 build 1244-79d6e57  the problem is still there (in the docker vanilla install) There's no checkbox to agree to the terms of use that will allow me to get past the password reset screen for the dataverseAdmin account.

**Comment by pdurbin** [comment]
@markwilkinson thanks, makes sense since the fix I mentioned above (#10440) didn't ship until v. 6.3.
